In [1]:
import pandas as pd
import requests
from config import api_key
import json

In [2]:
gop_candidate_df=pd.read_csv("2020_rep_candidate.csv")

In [6]:
url="https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/"

In [3]:
gop_can_id=gop_candidate_df.candidate_id
gop_can_id.to_list()

['S0AL00248',
 'S0VA00096',
 'S2TN00058',
 'S8MA00268',
 'S0VA00070',
 'S0MN00294',
 'S8NJ00012',
 'S0TX00365',
 'S0NH00326',
 'S0SD00088',
 'S8AZ00189',
 'S0TN00235',
 'S0SC00321',
 'S0TN00201',
 'S0AL00206',
 'S4WV00159',
 'S4MI00298',
 'S4LA00107',
 'S0IL00550',
 'S0NM00066',
 'S8MS00055',
 'S0GA00567',
 'S6ME00159',
 'S0TN00243',
 'S2TX00106',
 'S4AR00103',
 'S2TN00223',
 'S0IL00543',
 'S2MT00096',
 'S0DE00191',
 'S8MT00028',
 'S0VA00187',
 'S6WY00126',
 'S4IA00129',
 'S0VA00179',
 'S8NJ00541',
 'S0TN00185',
 'S0VA00146',
 'S0TN00151',
 'S4CO00395',
 'S0SC00149',
 'S0GA00658',
 'S0TN00169',
 'S0KS00349',
 'S0TN00276',
 'S6NC00308',
 'S0WY00186',
 'S0IL00501',
 'S0MN00286',
 'S8MS00261',
 'S4OK00083',
 'S0NE00080',
 'S8MI00372',
 'S0KY00461',
 'S0GA00492',
 'S0KS00257',
 'S0SC00313',
 'S0MT00157',
 'S0KS00208',
 'S0ME00095',
 'S0MN00328',
 'S0KS00240',
 'S0GA00526',
 'S0WY00137',
 'S6IL00185',
 'S0KS00315',
 'H6KS01179',
 'S0NM00090',
 'S0KS00331',
 'S0OK00438',
 'S0AZ00376',
 'S2KY00012',
 'S8AZ00221',
 'S0NJ00217',
 'S4NJ00250',
 'S0AL00289',
 'S0NH00334',
 'S4WY00147',
 'S0GA00534',
 'S0AL00263',
 'S0AL00297',
 'S0KY00297',
 'S0TN00250',
 'S0LA00352',
 'S0NH00318',
 'S0MA00232',
 'S0TN00326',
 'S4GA11285',
 'S4OR00156',
 'S0TN00219',
 'S0KS00281',
 'S0SC00297',
 'S0WY00178',
 'S8NM00200',
 'S8ID00092',
 'S6KS00080',
 'S0OR00337',
 'S0NM00124',
 'S4SD00049',
 'S0NM00116',
 'S4NE00090',
 'S0AL00271',
 'S6AL00195',
 'S0TN00144',
 'S0WY00160',
 'S0NJ00191',
 'S0SC00230',
 'S0OK00347',
 'S4TX00433',
 'S4AK00214',
 'S0IL00527',
 'S0GA00641',
 'S0VA00104',
 'S4NC00162',
 'S0AL00230',
 'S0NC00319',
 'S0KS00299',
 'S0RI00067',
 'S0WY00103',
 'S0WV00231']

In [4]:
def extract_data(results):
    return {
    "candidate_id":results["candidate_id"],
    "state": results["state"],
    "donation_count": results["count"],
    "total_raised": results["total"],
    "cycle": results["cycle"]
    }

In [7]:
gop_finance_3 = []
# pages=range(1,3)

for candidate in gop_can_id:
#     for page in range(1,3):

    data = requests.get(url=url, params={
        "election_full": False,
        "sort_hide_null": False,
        "cycle": 2020,
        "api_key": api_key,
        "sort_nulls_last": False,
        "sort_null_only": False,
        "per_page":  20,
        "candidate_id": candidate,
        "page": 3
        
    }).json()['results']
    
    for result in data:
        gop_finances_3 = extract_data(result)
    
        gop_finance_3.append(gop_finances_3)

In [8]:
gop_finances_3=pd.DataFrame(gop_finance_3)
gop_finances_3.head()

  candidate_id state  donation_count  total_raised  cycle
0    S8MA00268    WV               1        250.00   2020
1    S8MA00268    WY               2       1250.00   2020
2    S8MA00268    ZZ               4        195.00   2020
3    S0NH00326    TX              54      20375.65   2020
4    S0NH00326    UT               2         50.00   2020

In [9]:
gop_finance_2 = []
# pages=range(1,3)

for candidate in gop_can_id:
#     for page in range(1,3):

    data = requests.get(url=url, params={
        "election_full": False,
        "sort_hide_null": False,
        "cycle": 2020,
        "api_key": api_key,
        "sort_nulls_last": False,
        "sort_null_only": False,
        "per_page":  20,
        "candidate_id": candidate,
        "page": 2
        
    }).json()['results']
    
    for result in data:
        gop_finances_2 = extract_data(result)
    
        gop_finance_2.append(gop_finances_2)

In [10]:
gop_finances_2=pd.DataFrame(gop_finance_2)
gop_finances_2.head()

  candidate_id state  donation_count  total_raised  cycle
0    S8MA00268    MI               7       4500.00   2020
1    S8MA00268    MN               6        940.85   2020
2    S8MA00268    MO               2        490.00   2020
3    S8MA00268    MT               3       1500.00   2020
4    S8MA00268    NH               1       1000.00   2020

In [11]:
gop_finance_1 = []
# pages=range(1,3)

for candidate in gop_can_id:
#     for page in range(1,3):

    data = requests.get(url=url, params={
        "election_full": False,
        "sort_hide_null": False,
        "cycle": 2020,
        "api_key": api_key,
        "sort_nulls_last": False,
        "sort_null_only": False,
        "per_page":  20,
        "candidate_id": candidate,
        "page": 1
        
    }).json()['results']
    
    for result in data:
        gop_finances_1 = extract_data(result)
    
        gop_finance_1.append(gop_finances_1)

In [12]:
gop_finances_1=pd.DataFrame(gop_finance_1)
gop_finances_1.head()

  candidate_id state  donation_count  total_raised  cycle
0    S0AL00248    AL              11       1428.99   2020
1    S0VA00096    VA               2       3200.00   2020
2    S2TN00058    VA               2       5000.00   2020
3    S8MA00268    AL               1        250.00   2020
4    S8MA00268    AR               1        500.00   2020

In [13]:
concatting=[gop_finances_1, gop_finances_2, gop_finances_3]
new_gop_finance=pd.concat(concatting)
new_gop_finance.to_csv("2020_gop_finance_data.csv")