In [3]:
import pandas as pd

In [23]:
state_status=pd.read_csv("state_status.csv")

In [44]:
state_status.head()

  State status
0    AL    REP
1    AK    REP
2    AZ    REP
3    AR    REP
4    CA    DEM

In [25]:
candidates=pd.read_csv("2020_final_cand")

In [26]:
status=pd.DataFrame.merge(candidates,state_status, left_on="candidate_state", right_on="State")

In [45]:
status

,Unnamed: 0,name,candidate_id,candidate_state,party,incumbent_challenge_full,cycles,donation_count_in_state,total_raised_in_state,donation_count_out_of_state,total_raised_out_of_state,State,status
0,0,"AHLERS, DAN",S0SD00070,SD,DEM,Challenger,[2020],118.0,26585.00,6.0,6800.00,SD,REP
1,34,"HART, CLARA M MS",S0SD00096,SD,DEM,Challenger,[2020],1.0,400.00,NaN,NaN,SD,REP
2,8,"BORGLUM, SCYLLER",S0SD00088,SD,REP,Challenger,[2020],25.0,9471.48,24.0,18046.71,SD,REP
3,82,"ROUNDS, MIKE",S4SD00049,SD,REP,Incumbent,"[2012, 2014, 2016, 2018, 2020]",636.0,510260.97,669.0,753129.25,SD,REP
4,1,"BAER, DAN",S0CO00500,CO,DEM,Challenger,[2020],1138.0,285837.59,1225.0,837717.00,CO,DEM
...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,25,"DUNN, BLAINE P HON.",S0VA00187,VA,REP,Challenger,[2020],3.0,1750.00,1.0,1000.00,VA,DEM
191,28,"FAULKNER, OMARI",S0VA00179,VA,REP,Challenger,[2020],125.0,101131.65,91.0,41125.00,VA,DEM
192,30,"GADE, DANIEL MACARTHUR MR.",S0VA00146,VA,REP,Challenger,[2020],903.0,407304.02,290.0,212939.00,VA,DEM
193,94,"TAYLOR, SCOTT W.",S0VA00104,VA,REP,Challenger,[2020],173.0,126035.00,325.0,353544.00,VA,DEM
194,91,"SULLIVAN, DAN",S4AK00214,AK,REP,Incumbent,"[2014, 2016, 2018, 2020]",1571.0,868134.67,2754.0,3561713.42,AK,REP

In [46]:
can_status=status["party"]==status["status"]

In [47]:
can_status=can_status.to_frame()

In [54]:
can_status.head()

       0
0  False
1  False
2   True
3   True
4   True

In [60]:
candidates_2020=pd.DataFrame.merge(candidates,can_status, left_index=True,right_index=True)

In [61]:
candidates_2020

,Unnamed: 0,name,candidate_id,candidate_state,party,incumbent_challenge_full,cycles,donation_count_in_state,total_raised_in_state,donation_count_out_of_state,total_raised_out_of_state,0
0,0,"AHLERS, DAN",S0SD00070,SD,DEM,Challenger,[2020],118.0,26585.00,6.0,6800.00,False
1,1,"BAER, DAN",S0CO00500,CO,DEM,Challenger,[2020],1138.0,285837.59,1225.0,837717.00,False
2,2,"BALLARD, JACK",S0MT00116,MT,DEM,Challenger,[2020],13.0,4630.00,29.0,16450.00,True
3,3,"BELL, ROBERT CHRISTOPHER MR.",S0TX00324,TX,DEM,Challenger,[2020],537.0,312254.40,41.0,30609.00,True
4,4,"BEN DAVID, MERAV",S0WY00152,WY,DEM,Open seat,[2020],26.0,10785.00,33.0,15367.39,True
...,...,...,...,...,...,...,...,...,...,...,...,...
190,97,"TUCKER, GARLAND S III",S0NC00319,NC,REP,Challenger,[2020],727.0,440605.76,49.0,46225.00,False
191,98,"WAGLE, SUSAN",S0KS00299,KS,REP,Open seat,[2020],242.0,306690.47,84.0,45825.00,False
192,99,"WATERS, ALLEN",S0RI00067,RI,REP,Challenger,[2020],10.0,4510.00,2.0,3050.00,False
193,100,"WHEELER, JOSHUA B",S0WY00103,WY,REP,Open seat,[2020],7.0,5375.00,3.0,700.00,False
194,101,"WHITT, LARRY ALLEN II",S0WV00231,WV,REP,Challenger,[2020],8.0,4650.00,6.0,3250.00,True